// Generated by cubes-driver.js — DO NOT EDIT
// This file provides the Env type for Cloudflare Workers bindings and vars.
// Referenced by tsconfig.json: "types": ["./worker-configuration.d.ts"]

/// <reference types="@cloudflare/workers-types" />

interface Env {
	DB: D1Database;
	KYM_NANDA_EVIDENCE: R2Bucket;
	NANDA_NODE_CACHE: KVNamespace;
	KYM_NANDA_HMAC_SECRET: SecretsStoreSecret;
	KYM_NANDA_RADIUS_SECRET: SecretsStoreSecret;
	KYM_NANDA_ED25519_PRIVATE_KEY_v1: SecretsStoreSecret;
	CRON_AUTH_TOKEN: SecretsStoreSecret;
	NANDA_FEDERATION_ADMIN_KEY: SecretsStoreSecret;
	ASSETS: Fetcher;
	CERT_PASS_THRESHOLD: string;
	CERT_VALIDITY_DAYS: string;
	CONTACT_EMAIL_TO: string;
	ENVIRONMENT: string;
	EUR_TO_USD_RATE: string;
	FROM_EMAIL: string;
	LOG_LEVEL: string;
	NANDA_ED25519_PUBLIC_KEY_v1: string;
	NANDA_FEDERATION_PEER_URL: string;
	NANDA_NODE_ID: string;
	NANDA_REGISTRY_URL: string;
	NODE_ENV: string;
	NP_TO_USD_RATE: string;
	PAYMENT_PAYEE: string;
	SENTINEL_API_URL: string;
	SENTINEL_POST_AUTH_REDIRECT: string;
	SITE_NAME: string;
	SITE_OWNER_EMAIL: string;
	VITE_BASE_URL: string;
	[key: string]: unknown;
}
